### PR TITLE
Features/switchable diff value

### PR DESCRIPTION
**Pull request by aminm-net**
To include Changed field returns the original value 

Added required unit tests

### CODE REVIEW

**Comment by thehill383** [comment]
am i right that this hasn't updated the nuget package yet?

**Comment by aminm-net** [comment]
> am i right that this hasn't updated the nuget package yet?

Yes, I havn't pushed it there yet. So far I have merged the ability to make it configurable to switch changed values between original and modified in the result. Now I am finalizing the test for an additional feature with an alternative object model which exposes the changes as follow. Hopefuly on the weekend I complete the unit tests, merge that to the main, update the documentation and release in nuget. 
Does it work for you?

```
{
  "changed": {
    "x": [
      {
        "changed": {
          "foo": "bar"
        }
      },
      {
        "removed": {
          "baz": "qux"
        },
        "added": {
          "corge": "grault"
        }
      }
    ]
  }
}
```

Given:

```
{
  "x": [
    {
      "foo": "bar"
    },
    {
      "baz": "qux"
    }
  ]
}
```

And:

```
{
  "x": [
    {
      "foo": "quux"
    },
    {
      "corge": "grault"
    }
  ]
}
```

**Comment by thehill383** [comment]
yes, that's brilliant. definitely worth holding on for the alternative object model!
i look forward to giving it a try.
i am still investigating the content (PayPal) that i am using this against, either something is changing in the content or the data is managing to confuse JSONDiffer. If i find a scenario that doesn't seem to be giving the right response then presumably i would log that as an Issue, right?

**Comment by aminm-net** [comment]
Hi, I have pushed the changes to nuget, but only with the previous update for now. I will release the new object model shortly in a new version release.

**Comment by aminm-net** [comment]
> yes, that's brilliant. definitely worth holding on for the alternative object model! i look forward to giving it a try. i am still investigating the content (PayPal) that i am using this against, either something is changing in the content or the data is managing to confuse JSONDiffer. If i find a scenario that doesn't seem to be giving the right response then presumably i would log that as an Issue, right?
Hi, I have pushed the changes to nuget, but only with the previous update for now. I will release the new object model shortly in a new version release.

**Comment by aminm-net** [comment]
@thehill383
Just released the 1.0.0 version with the new object model both here and on nuget (should be on its way there in a couple of minute)

**Pull request merged**
